### ISSUE TITLE
🚸 Center introduction on the case in which a LaminDB instance already exists

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/lamin-docs#167]
Today I learned that some users forget to even authenticate with `lamin login` and to connect with `lamin connect`.

Given this is currently our biggest user target group, I think, we should prominently show in the quickstart how to login and connect.

This will hopefully be possible in just 2 or 3 lines.

@sunnyosun @Zethson -- WDYT?

(I would *not* duplicate this for the tutorial because I'm still pretty convinced that the tutorial should disappear and its content embedded into the introduction page.)

**Comment by Zethson** [comment]
Yes

**Comment by falexwolf** [comment]
Done meanwhile.
